export const MOCK_ORDER = {
  id: "ORD-8821",
  status: "COMPLETED",
  createdAt: "Oct 24, 2023 at 1:24 PM",
  items: [
    {
      id: "1",
      name: "Grilled Salmon",
      description: "With asparagus",
      qty: 1,
      price: 28.0,
      icon: "🐟",
    },
    {
      id: "2",
      name: "Caesar Salad",
      description: "Extra cheese",
      qty: 2,
      price: 12.5,
      icon: "🥗",
    },
    {
      id: "3",
      name: "White Wine Bottle",
      description: "Chardonnay",
      qty: 1,
      price: 45.0,
      icon: "🍷",
    },
    {
      id: "4",
      name: "Tiramisu",
      description: "Dessert",
      qty: 1,
      price: 14.0,
      icon: "🍰",
    },
  ],
  customer: {
    name: "John Doe",
    initials: "JD",
    type: "Regular Guest",
    table: "12",
    orderType: "Dine-in",
    guests: 2,
    server: "Sarah M.",
  },
  payment: {
    subtotal: 112.0,
    taxRate: 0.08,
    discount: 5.0,
    serviceFee: 5.6,
    cardLast4: "4242",
    tip: 20.94,
  },
  kitchenNote:
    "Customer has a nut allergy. Ensure no cross-contamination for the dessert.",
};

export const ALL_ORDERS = [
  MOCK_ORDER,
  {
    ...MOCK_ORDER,
    id: "ORD-8822",
    customer: {
      ...MOCK_ORDER.customer,
      name: "Alice Smith",
      initials: "AS",
      table: "04",
    },
    items: [
      {
        id: "1",
        name: "Burger & Fries",
        description: "Medium rare",
        qty: 1,
        price: 18.5,
        icon: "🍔",
      },
    ],
    createdAt: "Oct 24, 2023 at 2:10 PM",
  },
  {
    ...MOCK_ORDER,
    id: "ORD-8823",
    customer: {
      ...MOCK_ORDER.customer,
      name: "Bob Wilson",
      initials: "BW",
      table: "08",
    },
    items: [
      {
        id: "1",
        name: "Margherita Pizza",
        description: "Thin crust",
        qty: 1,
        price: 22.0,
        icon: "🍕",
      },
    ],
    createdAt: "Oct 24, 2023 at 3:15 PM",
  },
  {
    ...MOCK_ORDER,
    id: "ORD-8824",
    customer: {
      ...MOCK_ORDER.customer,
      name: "Charlie Day",
      initials: "CD",
      table: "15",
    },
    items: [
      {
        id: "1",
        name: "Steak Frites",
        description: "Medium",
        qty: 1,
        price: 34.0,
        icon: "🥩",
      },
    ],
    createdAt: "Oct 24, 2023 at 4:30 PM",
  },
  {
    ...MOCK_ORDER,
    id: "ORD-8825",
    status: "PENDING",
    customer: {
      ...MOCK_ORDER.customer,
      name: "Diana Prince",
      initials: "DP",
      table: "22",
    },
    items: [
      {
        id: "1",
        name: "Pasta Carbonara",
        description: "Fresh pasta",
        qty: 1,
        price: 19.0,
        icon: "🍝",
      },
    ],
    createdAt: "Oct 24, 2023 at 5:00 PM",
  },
  {
    ...MOCK_ORDER,
    id: "ORD-8826",
    customer: {
      ...MOCK_ORDER.customer,
      name: "Evan Wright",
      initials: "EW",
      table: "01",
    },
    items: [
      {
        id: "1",
        name: "Greek Salad",
        description: "Feta cheese",
        qty: 1,
        price: 14.5,
        icon: "🥗",
      },
    ],
    createdAt: "Oct 24, 2023 at 6:15 PM",
  },
];

export const RANGE_DATA = {
  Today: [
    { name: "08:00", orders: 4 },
    { name: "10:00", orders: 12 },
    { name: "12:00", orders: 28 },
    { name: "14:00", orders: 15 },
    { name: "16:00", orders: 9 },
    { name: "18:00", orders: 32 },
    { name: "20:00", orders: 45 },
    { name: "22:00", orders: 18 },
  ],
  "This Week": [
    { name: "Mon", orders: 120 },
    { name: "Tue", orders: 145 },
    { name: "Wed", orders: 110 },
    { name: "Thu", orders: 160 },
    { name: "Fri", orders: 240 },
    { name: "Sat", orders: 280 },
    { name: "Sun", orders: 190 },
  ],
  "This Month": [
    { name: "Week 1", orders: 850 },
    { name: "Week 2", orders: 920 },
    { name: "Week 3", orders: 1100 },
    { name: "Week 4", orders: 980 },
  ],
  "This Year": [
    { name: "Jan", orders: 3200 },
    { name: "Feb", orders: 2800 },
    { name: "Mar", orders: 3500 },
    { name: "Apr", orders: 3100 },
    { name: "May", orders: 4200 },
    { name: "Jun", orders: 3900 },
    { name: "Jul", orders: 4500 },
    { name: "Aug", orders: 4800 },
    { name: "Sep", orders: 4100 },
    { name: "Oct", orders: 4600 },
    { name: "Nov", orders: 5200 },
    { name: "Dec", orders: 6100 },
  ],
};
